### ISSUE TITLE
is there any pretrain model

### ISSUE THREAD

**Issue by flashsupporter** [AvishagS422/PhantomSponges#1]
hello AvishagS422,
Could you share prebuild model? If available, could you please email to flashsupporter@gmail.com!
Thanks a lot for sharing

**Comment by AvishagS422** [comment]
Hi Flashsupporter,
What do you mean by a prebuild model? 
We used the pretrained models provided by [ultralytics](https://docs.ultralytics.com/models/).

**Comment by flashsupporter** [comment]
Hi AvishagS422,

Sorry for misunderstanding your code. I have managed to run your code successfully.

Thank you so much!

**Comment by AvishagS422** [comment]
You're welcome:)

**Comment by AvishagS422** [comment]
You're welcome:)

**Comment by ShuchunXu** [comment]
@flashsupporter Hello, was the dataset preprocessed? The download path for the dataset provided in the readme file is no longer accessible.
